#!/bin/sh

export CHROME_DEVEL_SANDBOX=/usr/sbin/chrome-devel-sandbox
if [ "${USER}" = "root" ] ; then 
	/usr/bin/chrome/chrome --user-data-dir=${HOME}/.chromium/ $@
else
	/usr/bin/chrome/chrome $@
fi
