name: Firefox build- and smoke-test

on:
  workflow_dispatch:
    inputs:
      repository_owner:
        description: 'Repository owner (e.g., OSSystems, brightsign)'
        required: true
        default: 'OSSystems'
      branch:
        description: 'Branch to checkout for the workflow'
        required: true
        default: 'master'
  pull_request:
    branches:
      - master
    paths:
      - 'meta-firefox/**'

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build:
    if: ${{ github.repository_owner == 'OSSystems' }}
    strategy:
      matrix:
        yocto_version: [scarthgap, wrynose, master]
        ff_version: [esr, latest]
        arch: [arm, aarch64, riscv, x86-64]
    runs-on: [self-hosted, firefox]
    container:
      image: skandigraun/yocto:latest
      volumes:
        - yocto:/yocto
        - cocto:/cocto
    steps:
      - run: |
         libc_list="glibc musl"
         display_list="x11 wayland"
         libc=$(echo $libc_list | tr ' ' '\n' | shuf -n1)
         display_system=$(echo $display_list | tr ' ' '\n' | shuf -n1)
         # avoid arm32+musl+wayland combo, because core-image-weston is broken:
         # https://bugzilla.yoctoproject.org/show_bug.cgi?id=16334
         # (It works on Scarthgap though)
         if [ "${{ matrix.yocto_version }}" = "master" -o "${{ matrix.yocto_version }}" = "wrynose" ]; then
             while [ "${{ matrix.arch }}" = "arm" -a "${libc}" = "musl" -a "${display_system}" = "wayland" ]; do
                 libc=$(echo $libc_list | tr ' ' '\n' | shuf -n1)
                 display_system=$(echo $display_list | tr ' ' '\n' | shuf -n1)
             done
         fi
         mkdir -p /yocto/${{ matrix.yocto_version }}
         cd /yocto/${{ matrix.yocto_version }}
         rm -rf meta-browser meta-firefox-test
         if [ "${{ github.event_name }}" = "pull_request" ]; then
             GH_URL="$GITHUB_SERVER_URL/${{ github.event.pull_request.head.repo.full_name }}"
             GH_REV="$GITHUB_HEAD_REF"
         else
             GH_URL="$GITHUB_SERVER_URL/${{ github.event.inputs.repository_owner }}/meta-browser"
             GH_REV="${{ github.event.inputs.branch }}"
         fi
         git clone $GH_URL
         git -C meta-browser checkout $GH_REV
         # clone the test repo
         git clone https://github.com/OldManYellsAtCloud/meta-firefox-test.git
         ./meta-firefox-test/scripts/build.sh ${{ matrix.yocto_version }} ${{ matrix.arch }} ${{ matrix.ff_version }} ${libc} ${display_system}
  test:
    if: ${{ github.repository_owner == 'OSSystems' }}
    runs-on: [self-hosted, firefox]
    needs: build
    strategy:
      matrix:
        yocto_version: [scarthgap, wrynose, master]
        ff_version: [esr, latest]
        arch: [arm, aarch64, riscv, x86-64]
    steps:
      - run: |
         cd /yocto/${{ matrix.yocto_version }}
         ./meta-firefox-test/scripts/test.sh ${{ matrix.yocto_version}} ${{ matrix.arch }} ${{ matrix.ff_version }}
